apiVersion: v1
kind: Service
metadata:
  name: milvus-datacoord
  namespace: milvus
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 13333
      protocol: TCP
      targetPort: 13333
  selector:
    app: milvus-datacoord
  sessionAffinity: None
  type: ClusterIP
