apiVersion: v1
kind: Service
metadata:
  name: pulsar
  namespace: milvus
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: pulsar
      port: 6650
      protocol: TCP
      targetPort: 6650
    - name: http
      port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: pulsar
  sessionAffinity: None
  type: ClusterIP
