apiVersion: v1
kind: Service
metadata:
  name: mcp-company1
  namespace: rag-spoke
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: mcp-company1
  sessionAffinity: None
  type: ClusterIP
