apiVersion: v1
kind: Service
metadata:
  name: pdf-converter
  namespace: pdf-converter
  labels:
    app: pdf-converter
spec:
  type: ClusterIP
  selector:
    app: pdf-converter
  ports:
  - name: http
    port: 8000
    targetPort: 8000
    protocol: TCP
