apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-mirror-efs
  namespace: milvus
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-client
  resources:
    requests:
      storage: 500Gi
