apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opensearch-data
  namespace: opensearch
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 64Gi
  storageClassName: local-path
  volumeMode: Filesystem
