apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: etcd-data-local
  namespace: milvus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeMode: Filesystem
