apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-data-local
  namespace: milvus
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Gi
  storageClassName: local-path
  volumeMode: Filesystem
