apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memgraph-data
  namespace: rag-spoke
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
  storageClassName: local-path
  volumeMode: Filesystem
