apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: model-cache
  namespace: rag-spoke
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 8Gi
