apiVersion: v1
kind: Service
metadata:
  name: valkey
  namespace: valkey
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 6379
      protocol: TCP
      targetPort: 6379
  selector:
    app: valkey
  sessionAffinity: None
  type: ClusterIP
