apiVersion: v1
kind: Service
metadata:
  name: opensearch
  namespace: opensearch
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: http
      port: 9200
      protocol: TCP
      targetPort: 9200
    - name: transport
      port: 9300
      protocol: TCP
      targetPort: 9300
  selector:
    app: opensearch
  sessionAffinity: None
  type: ClusterIP
