apiVersion: v1
kind: Service
metadata:
  name: ollama
  namespace: rag
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 11434
      protocol: TCP
      targetPort: 11434
      nodePort: 31434
  selector:
    app: ollama
  sessionAffinity: None
  type: NodePort
