apiVersion: v1
kind: Service
metadata:
  name: rag-task-worker
  namespace: rag-company1
spec:
  selector:
    app: rag-task-worker
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
  type: ClusterIP
