apiVersion: v1
kind: Service
metadata:
  name: fleet-ui
  namespace: fleet-ui
  labels:
    app: fleet-ui
spec:
  type: ClusterIP
  selector:
    app: fleet-ui
  ports:
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
