apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: memgraph-data
  namespace: memgraph
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
  storageClassName: local-path
  volumeMode: Filesystem
