apiVersion: v1
kind: Service
metadata:
  name: memgraph
  namespace: memgraph
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - name: bolt
      port: 7687
      protocol: TCP
      targetPort: 7687
    - name: websocket
      port: 7444
      protocol: TCP
      targetPort: 7444
  selector:
    app: memgraph
  sessionAffinity: None
  type: ClusterIP
