apiVersion: v1
kind: Service
metadata:
  name: rag-backend-kernel
  namespace: rag-company1
spec:
  type: ClusterIP
  selector:
    app: rag-backend-kernel
  ports:
    - name: http
      port: 8000
      targetPort: 8000
      protocol: TCP
