apiVersion: v1
kind: Service
metadata:
  name: nemo-guardrails
  namespace: guardrails
spec:
  internalTrafficPolicy: Cluster
  ipFamilies:
    - IPv4
  ipFamilyPolicy: SingleStack
  ports:
    - port: 8000
      protocol: TCP
      targetPort: 8000
  selector:
    app: nemo-guardrails
  sessionAffinity: None
  type: ClusterIP
